const mockDbData = [
  {
    id: 1,
    title: "medical bill",
    date: "20-05-2022",
    user: "vinoth",
    amount: 3000,
    type: "health",
  },
  {
    id: 2,
    title: "monthly grocery purchase",
    date: "22-05-2022",
    user: "murugan",
    amount: 5500,
    type: "grocery",
  },
  {
    id: 3,
    title: "Dress purchase",
    date: "25-05-2022",
    user: "vinoth",
    amount: 2098,
    type: "clothing",
  },
  {
    id: 4,
    title: "Dinner",
    date: "25-05-2022",
    user: "vinoth",
    amount: 3256,
    type: "food",
  },
  {
    id: 5,
    title: "Beast movie",
    date: "29-05-2022",
    user: "murugan",
    amount: "6340",
    type: "entertainment",
  },
  {
    id: 6,
    title: "gendral health checkup",
    date: "02-06-2022",
    user: "vinoth",
    amount: 1699,
    type: "health",
  },
  {
    id: 1,
    title: "medical bill",
    date: "20-05-2022",
    user: "vinoth",
    amount: 3000,
    type: "health",
  },
  {
    id: 2,
    title: "monthly grocery purchase",
    date: "22-05-2022",
    user: "murugan",
    amount: 5500,
    type: "grocery",
  },
  {
    id: 3,
    title: "Dress purchase",
    date: "25-05-2022",
    user: "vinoth",
    amount: 2098,
    type: "clothing",
  },
  {
    id: 4,
    title: "Dinner",
    date: "25-05-2022",
    user: "vinoth",
    amount: 3256,
    type: "food",
  },
  {
    id: 5,
    title: "Beast movie",
    date: "29-05-2022",
    user: "murugan",
    amount: "6340",
    type: "entertainment",
  },
  {
    id: 6,
    title: "gendral health checkup",
    date: "02-06-2022",
    user: "vinoth",
    amount: 1699,
    type: "health",
  },
  {
    id: 1,
    title: "medical bill",
    date: "20-05-2022",
    user: "vinoth",
    amount: 3000,
    type: "health",
  },
  {
    id: 2,
    title: "monthly grocery purchase",
    date: "22-05-2022",
    user: "murugan",
    amount: 5500,
    type: "grocery",
  },
  {
    id: 3,
    title: "Dress purchase",
    date: "25-05-2022",
    user: "vinoth",
    amount: 2098,
    type: "clothing",
  },
  {
    id: 4,
    title: "Dinner",
    date: "25-05-2022",
    user: "vinoth",
    amount: 3256,
    type: "food",
  },
  {
    id: 5,
    title: "Beast movie",
    date: "29-05-2022",
    user: "murugan",
    amount: "6340",
    type: "entertainment",
  },
  {
    id: 6,
    title: "gendral health checkup",
    date: "02-06-2022",
    user: "vinoth",
    amount: 1699,
    type: "health",
  },
  {
    id: 1,
    title: "medical bill",
    date: "20-05-2022",
    user: "vinoth",
    amount: 3000,
    type: "health",
  },
  {
    id: 2,
    title: "monthly grocery purchase",
    date: "22-05-2022",
    user: "murugan",
    amount: 5500,
    type: "grocery",
  },
  {
    id: 3,
    title: "Dress purchase",
    date: "25-05-2022",
    user: "vinoth",
    amount: 2098,
    type: "clothing",
  },
  {
    id: 4,
    title: "Dinner",
    date: "25-05-2022",
    user: "vinoth",
    amount: 3256,
    type: "food",
  },
  {
    id: 5,
    title: "Beast movie",
    date: "29-05-2022",
    user: "murugan",
    amount: "6340",
    type: "entertainment",
  },
  {
    id: 6,
    title: "gendral health checkup",
    date: "02-06-2022",
    user: "vinoth",
    amount: 1699,
    type: "health",
  },

  {
    id: 7,
    title: "monthly grocery purchase",
    date: "19-06-2022",
    user: "murugan",
    amount: 5671,
    type: "grocery",
  },
];
module.exports = mockDbData;
